
package payment_relay

import (
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"
	"github.com/antihax/optional"
)

// Linger please
var (
	_ context.Context
)

type TransactionApiService service
/*
TransactionApiService Get transaction status
Resource that will retrieve transaction status based on topup reference id, payment reference id, or client reference id
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param xAuthHeader Consumer ACL Key
 * @param optional nil or *TransactionApiTransactionStatusGetOpts - Optional Parameters:
     * @param "PaymentRefId" (optional.String) -  IH Relay Transaction Reference ID
     * @param "ClientRefId" (optional.String) -  Client Transaction Reference ID
     * @param "ProviderRefId" (optional.String) -  Reference ID generated by Provider to help identify the transaction as needed in settlement reports and such
     * @param "PaymentId" (optional.String) -  Topup Reference ID
     * @param "RefId" (optional.String) -  (For Prefund Consumer) Topup Processor Reference ID
@return TransactionStatus
*/

type TransactionApiTransactionStatusGetOpts struct {
    PaymentRefId optional.String
    ClientRefId optional.String
    ProviderRefId optional.String
    PaymentId optional.String
    RefId optional.String
}

func (a *TransactionApiService) TransactionStatusGet(ctx context.Context, xAuthHeader string, localVarOptionals *TransactionApiTransactionStatusGetOpts) (TransactionStatus, *http.Response, error) {
	var (
		localVarHttpMethod = strings.ToUpper("Get")
		localVarPostBody   interface{}
		localVarFileName   string
		localVarFileBytes  []byte
		localVarReturnValue TransactionStatus
	)

	// create path and map variables
	localVarPath := a.client.cfg.BasePath + "/transaction/status"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if localVarOptionals != nil && localVarOptionals.PaymentRefId.IsSet() {
		localVarQueryParams.Add("payment_ref_id", parameterToString(localVarOptionals.PaymentRefId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.ClientRefId.IsSet() {
		localVarQueryParams.Add("client_ref_id", parameterToString(localVarOptionals.ClientRefId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.ProviderRefId.IsSet() {
		localVarQueryParams.Add("provider_ref_id", parameterToString(localVarOptionals.ProviderRefId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.PaymentId.IsSet() {
		localVarQueryParams.Add("payment_id", parameterToString(localVarOptionals.PaymentId.Value(), ""))
	}
	if localVarOptionals != nil && localVarOptionals.RefId.IsSet() {
		localVarQueryParams.Add("ref_id", parameterToString(localVarOptionals.RefId.Value(), ""))
	}
	// to determine the Content-Type header
	localVarHttpContentTypes := []string{}

	// set Content-Type header
	localVarHttpContentType := selectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}

	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHttpHeaderAccept := selectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	localVarHeaderParams["X-Auth-Header"] = parameterToString(xAuthHeader, "")
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHttpResponse, err := a.client.callAPI(r)
	if err != nil || localVarHttpResponse == nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHttpResponse.Body)
	localVarHttpResponse.Body.Close()
	if err != nil {
		return localVarReturnValue, localVarHttpResponse, err
	}

	if localVarHttpResponse.StatusCode < 300 {
		// If we succeed, return the data, otherwise pass on to decode error.
		err = a.client.decode(&localVarReturnValue, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
		if err == nil { 
			return localVarReturnValue, localVarHttpResponse, err
		}
	}

	if localVarHttpResponse.StatusCode >= 300 {
		newErr := GenericSwaggerError{
			body: localVarBody,
			error: localVarHttpResponse.Status,
		}
		if localVarHttpResponse.StatusCode == 200 {
			var v TransactionStatus
			err = a.client.decode(&v, localVarBody, localVarHttpResponse.Header.Get("Content-Type"));
				if err != nil {
					newErr.error = err.Error()
					return localVarReturnValue, localVarHttpResponse, newErr
				}
				newErr.model = v
				return localVarReturnValue, localVarHttpResponse, newErr
		}
		return localVarReturnValue, localVarHttpResponse, newErr
	}

	return localVarReturnValue, localVarHttpResponse, nil
}
