package payment_relay

// Transaction Reference IDs
type Response3DetailsReference struct {
	// Reference ID generated by Relay to return back to the consumer
	PaymentRefId string `json:"payment_ref_id,omitempty"`
	// Reference ID that consumer can pass to identify the transaction
	ClientRefId string `json:"client_ref_id,omitempty"`
	// Transaction reference identifier from OP
	RefId string `json:"ref_id,omitempty"`
	// Topup transaction reference identifier
	PaymentId string `json:"payment_id,omitempty"`
}
