package payment_relay

type TransactionItem struct {
	// Transaction Unique Identifier
	Id string `json:"id,omitempty"`
	// Provider Hash ID
	ProviderId string `json:"provider_id,omitempty"`
	// Provider Name
	ProviderName string `json:"provider_name,omitempty"`
	// IH Relay Transaction Reference ID
	PaymentRefId string `json:"payment_ref_id,omitempty"`
	// Client Transaction Reference ID
	ClientRefId string `json:"client_ref_id,omitempty"`
	// Reference ID generated by Provider to help identify the transaction as needed in settlement reports and such
	ProviderRefId string `json:"provider_ref_id,omitempty"`
	// Refund Reference ID
	RefundRefId string `json:"refund_ref_id,omitempty"`
	// Topup Reference ID
	PaymentId string `json:"payment_id,omitempty"`
	// (For Prefund Consumer) Topup Processor Reference ID
	RefId string `json:"ref_id,omitempty"`
	// Status ID
	StatusId string `json:"status_id,omitempty"`
	// Status Name
	Status string `json:"status,omitempty"`
	// Status Description
	Message string `json:"message,omitempty"`
	RefundDetails *TransactionItemRefundDetails `json:"refund_details,omitempty"`
	// Topup Amount
	Amount string `json:"amount,omitempty"`
	Fee *TransactionItemFee `json:"fee,omitempty"`
	User *TransactionStatusDetailsUser `json:"user,omitempty"`
	Source *TransactionStatusDetailsSource `json:"source,omitempty"`
	// Payment Provider Status Inquiry
	Details *interface{} `json:"details,omitempty"`
	// Expiry Date until Transaction will be released from hold state
	DateHoldingExpiry string `json:"date_holding_expiry,omitempty"`
	// Date when transaction was flagged as risk
	DateFlaggedRisk string `json:"date_flagged_risk,omitempty"`
	// Date when transaction was blacklisted
	DateBlacklisted string `json:"date_blacklisted,omitempty"`
	// Date when transaction was refunded
	DateRefunded string `json:"date_refunded,omitempty"`
	// Transaction Date
	DateCreated string `json:"date_created,omitempty"`
	// Transaction Date Updated
	DateModified string `json:"date_modified,omitempty"`
}
