package payment_relay

type TransactionStatus struct {
	// IH Relay Transaction Reference ID
	PaymentRefId string `json:"payment_ref_id"`
	// Client Transaction Reference ID
	ClientRefId string `json:"client_ref_id"`
	// Reference ID generated by Provider to help identify the transaction as needed in settlement reports and such
	ProviderRefId string `json:"provider_ref_id,omitempty"`
	// Topup Reference ID
	PaymentId string `json:"payment_id"`
	// (For Prefund Consumer) Topup Processor Reference ID
	RefId string `json:"ref_id"`
	// Transaction status
	Status string `json:"status"`
	// Transaction status description
	Message string `json:"message"`
	Details *TransactionStatusDetails `json:"details,omitempty"`
}
